// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYwHBAifqggDIgJGli9OR1OOII7qVCa7g',
    appId: '1:894461567350:web:8504624185290262599a57',
    messagingSenderId: '894461567350',
    projectId: 'flutter-c4365',
    authDomain: 'flutter-c4365.firebaseapp.com',
    storageBucket: 'flutter-c4365.firebasestorage.app',
    measurementId: 'G-74C3GN2LFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7MiZcNvu6IByW9WM94awokEVZgN9t97o',
    appId: '1:894461567350:android:a9b7ece5088a428a599a57',
    messagingSenderId: '894461567350',
    projectId: 'flutter-c4365',
    storageBucket: 'flutter-c4365.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXbdEvXIoxkHwa-vRCwG2h1lsv92P61B4',
    appId: '1:894461567350:ios:e57fe0a7be81ee66599a57',
    messagingSenderId: '894461567350',
    projectId: 'flutter-c4365',
    storageBucket: 'flutter-c4365.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXbdEvXIoxkHwa-vRCwG2h1lsv92P61B4',
    appId: '1:894461567350:ios:e57fe0a7be81ee66599a57',
    messagingSenderId: '894461567350',
    projectId: 'flutter-c4365',
    storageBucket: 'flutter-c4365.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYwHBAifqggDIgJGli9OR1OOII7qVCa7g',
    appId: '1:894461567350:web:f13d0c30cb86315d599a57',
    messagingSenderId: '894461567350',
    projectId: 'flutter-c4365',
    authDomain: 'flutter-c4365.firebaseapp.com',
    storageBucket: 'flutter-c4365.firebasestorage.app',
    measurementId: 'G-38ZSXCWGSD',
  );
}
